### ISSUE TITLE
CropBlock Mixin Exception

### ISSUE THREAD

**Issue by smolinacadena** [ModdingForBlockheads/Forbic#32]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

net.minecraftforge:forge:1.18.2-40.1.48

### Mod Version

net.blay09.mods:balm:3.2.0+305

### Describe the Issue

Hi @blay09 

I'm the developer of Refined Cooking (mod that connects Cooking for Blockhead and Refined Storage). I've been trying to update my mod to 1.18.2 and managed to build/compile my mod. I added Balm as a new dependency for my project while I was updating it (through GPR).

The issue I get is at runtime/execution. For some reason I get an error with the CropBlock Mixin from Balm and I can't run the server or client to test my updates.

I've tested with different Mod Loader versions (40.0.24, 41.1.0, 41.1.48) but no luck. I also tested importing the dependency with CurseMaven with the same results.

Would you be able to check this out? 

### Logs

https://pastebin.com/QrGTYsC6

**Comment by BlayTheNinth** [comment]
I don't really know much about Mixin, though I assume this may be related to #23 which has a similar mixin issue but on Fabric.

I wonder if it's maybe a mappings mismatch? Are you using mojang mappings in your mod? Is it maybe not correctly deobfing Balm / its mixins?

Otherwise there may be people on the Forge discord who know more about these kind of issues. When I depend on Balm I don't have to do anything special other than [specifying the Mixin arguments for the run configuration](https://github.com/ModdingForBlockheads/CookingForBlockheads/blob/1.19.x/forge/build.gradle#L26-L113) and [the dependency](https://github.com/ModdingForBlockheads/CookingForBlockheads/blob/1.19.x/forge/build.gradle#L129).

**Comment by smolinacadena** [comment]
Thanks @blay09 

I ran it again today without any changes and it works. Maybe some cache thing or something.
