### ISSUE TITLE
when i put in balm minecraft wont start at all

### ISSUE THREAD

**Issue by the-biggest-birfd** [ModdingForBlockheads/Forbic#59]
### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Mod Loader Version

1.0.25

### Mod Version

multiple mods

### Balm Version

7.1.4

### Describe the Issue

minecraft just wont start

### Logs

no logs at all

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

mainly sodium

**Comment by the-biggest-birfd** [comment]
wait sorry client tweaks with version 11.1.0

**Comment by the-biggest-birfd** [comment]
it just says waiting for log out put and doesn't do jack shit

**Comment by the-biggest-birfd** [comment]
im using mac os sonoma btw

**Comment by BlayTheNinth** [comment]
Please provide the full logs. You can find the logs in the `logs` directory of the client or server. Most of the time `latest.log` is the correct file (unless the crash or issue happened during an earlier run).

Logs can be uploaded here by dragging the file into the comment field, or you can post them on a site like https://gist.github.com/ or https://pastebin.com/. Make sure they are set to be `public` (or unlisted) and to `never expire`.

---

If Minecraft refuses to start at all, it seems to be an issue with your launcher, since the mods don't load that early and if they did load, there would be log output.

**Comment by the-biggest-birfd** [comment]
sorry, it was a problem with a mod called [deathlog](https://modrinth.com/mod/deathlog). on a unrelated note, if you could, I removed deathlog, and there's other problems, mind checking it out for me? thanks! 
[crash-2023-10-12_18.45.40-client copy.txt](https://github.com/TwelveIterationMods/Balm/files/12880547/crash-2023-10-12_18.45.40-client.copy.txt)
